In [3]:
#importing files
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [6]:
#read csv file
df=pd.read_csv("Dangue-Trend-Nepl-Nov2022.csv")
df.head()

,Unnamed: 0,Province,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Grand Total,Code,District
0,0,3.0,0,0,0,0,1,1,35,727,9891,2911,561,14127,306,KATHMANDU
1,1,3.0,0,0,0,0,0,1,99,1558,6016,1809,120,9603,308,LALITPUR
2,2,3.0,0,0,0,0,0,0,6,86,1151,4204,677,6124,307,BHAKTAPUR
3,3,3.0,0,0,0,0,0,0,221,337,2452,2220,546,5776,312,MAKWANPUR
4,4,3.0,0,0,0,0,0,3,4,24,995,1509,624,3159,313,CHITAWAN

In [7]:
df.shape

(78, 16)